"""empty message

Revision ID: ed47e2493675
Revises: 
Create Date: 2022-07-22 11:06:42.208111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed47e2493675'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Departement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDirection', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('nameDirection', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['idDirection'], ['Direction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('SubCategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('idCategory', sa.Integer(), nullable=True),
    sa.Column('nameCategory', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['idCategory'], ['Category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('Format', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('creator', sa.String(length=200), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('tag', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('lastModification', sa.DateTime(), nullable=False),
    sa.Column('modificatorId', sa.Integer(), nullable=True),
    sa.Column('creatorId', sa.Integer(), nullable=True),
    sa.Column('idSubCategory', sa.Integer(), nullable=True),
    sa.Column('idCategory', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idSubCategory'], ['SubCategory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDepartement', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('nameDepartement', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['idDepartement'], ['Departement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDocument', sa.Integer(), nullable=True),
    sa.Column('idRole', sa.Integer(), nullable=True),
    sa.Column('read', sa.Integer(), nullable=False),
    sa.Column('write', sa.Integer(), nullable=False),
    sa.Column('update', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idDocument'], ['Document.id'], ),
    sa.ForeignKeyConstraint(['idRole'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=200), nullable=False),
    sa.Column('l_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('activate_acc', sa.Integer(), nullable=True),
    sa.Column('idRole', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idRole'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('Access')
    op.drop_table('Role')
    op.drop_table('Document')
    op.drop_table('SubCategory')
    op.drop_table('Departement')
    op.drop_table('Direction')
    op.drop_table('Category')
    # ### end Alembic commands ###
